name: Aza Man CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create data folder and placeholder files
        run: |
          mkdir -p data
          touch data/.keep
          echo "Input,Output" > data/finance_eval_dataset.csv
          echo "Set my username to testuser,Username set to testuser" >> data/finance_eval_dataset.csv

      - name: Run pytest tests
        env:
          PYTHONPATH: .
          DATA_PATH: ./data/azaman.db
        run: |
          pytest tests/ -v

      - name: Run evaluation tests
        env:
          PYTHONPATH: .
          TOGETHER_API_KEY: ${{ secrets.TOGETHER_API_KEY }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          DATA_PATH: ./data/azaman.db
        run: |
          python evals.py

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create data folder and placeholder
        run: |
          mkdir -p data
          touch data/.keep