[global]
developmentMode = false

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[theme]
base = "dark"
primaryColor = "#FF0000"
backgroundColor = "#000000"
secondaryBackgroundColor = "#1C2526"
textColor = "#FFFFFF"
font = "sans serif"